### ISSUE TITLE
Problema com a destruição dos inimigos ao atirar no jogo Space Invaders

### ISSUE THREAD

**Issue by theMyntt** [lmaurici0/Space-Invaders#1]
Eu, como usuário do jogo Space Invaders desenvolvido em Python pelo Imaurici0, deparei-me com um problema na mecânica de destruição dos inimigos quando atiro. O objetivo do jogo é eliminar todos os inimigos invasores antes que eles cheguem à parte inferior da tela.

No entanto, notei que, em algumas situações, os inimigos não são destruídos mesmo quando atiro diretamente neles. Isso resulta em uma experiência de jogo frustrante, já que meus tiros deveriam eliminar os inimigos e progredir para o próximo nível.

Passos para reproduzir o problema:

Inicie o jogo Space Invaders.
Mova a nave do jogador para uma posição em que um inimigo esteja alinhado.
Pressione o botão de tiro para disparar contra o inimigo.
Observe que, em certos casos, o inimigo não é destruído e continua se movendo normalmente.
Comportamento esperado:

Quando o jogador atira em um inimigo, o tiro deveria colidir com o inimigo e destruí-lo, removendo-o da tela. Dessa forma, o jogador pode progredir no jogo eliminando todos os inimigos.

Comportamento atual:

Em alguns casos, quando atiro em um inimigo, o tiro atravessa o inimigo sem destruí-lo, resultando na continuidade do movimento do inimigo e impossibilitando a progressão adequada no jogo.

Possíveis soluções:

Verificar a lógica de colisão entre o tiro e o inimigo para garantir que a detecção esteja ocorrendo corretamente.
Rever o código responsável pela destruição dos inimigos, verificando se todas as condições necessárias estão sendo consideradas.
Testar diferentes abordagens de colisão e verificação de destruição para encontrar a solução mais eficaz.
Realizar testes extensivos para identificar os cenários específicos em que o problema ocorre com mais frequência, a fim de isolar e corrigir a causa raiz do problema.
Observações adicionais:

A correção desse problema é crucial para a experiência do usuário no jogo Space Invaders, pois afeta diretamente a jogabilidade e a progressão no jogo. Agradecemos antecipadamente por sua atenção e trabalho na resolução desse problema.

**Comment by xgheter** [comment]
Meu deus 💀

**Comment by lmaurici0** [comment]
pronto, não está mais
